name: 'Setup Go with Cache'

description: 'Setup Go environment with module caching'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: ''
  go-version-file:
    description: 'Path to go.mod file for version'
    required: false
    default: ''

outputs:
  go-version:
    description: 'The installed Go version'
    value: ${{ steps.setup.outputs.go-version }}

runs:
  using: 'composite'
  steps:
  - name: Set up Go
    id: setup
    uses: actions/setup-go@v5
    with:
      go-version: ${{ inputs.go-version }}
      go-version-file: ${{ inputs.go-version-file }}

  - name: Cache Go modules
    uses: actions/cache@v4
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-go-${{ steps.setup.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-${{ steps.setup.outputs.go-version }}-

  - name: Download dependencies
    shell: bash
    run: |
      go mod download
      if [ -d "test" ]; then
        cd test && go mod download
      fi
